import { FormEvent, useEffect, useMemo, useState } from 'react';
import { Link, Navigate, Route, Routes, useLocation, useNavigate, useParams } from 'react-router-dom';
import { demoRoles, permissions, records } from './mocks/data';
import { patientService } from './services/patientService';
import { smsService } from './services/smsService';
import type { DemoUser, Patient, Role } from './types';

const nav=[['/dashboard','⌂','Tableau de bord'],['/patients','♙','Patients'],['/consultations','⚕','Consultations'],['/appointments','◷','Rendez-vous'],['/laboratory','⌁','Laboratoire'],['/imaging','◉','Imagerie'],['/hospitalizations','✚','Hospitalisation'],['/prescriptions','▤','Ordonnances'],['/documents','▧','Documents'],['/sms','✉','SMS'],['/users','♧','Utilisateurs'],['/audit','◫','Audit'],['/settings','⚙','Paramètres']];
const dmeTabs=['Résumé','Consultations','Antécédents','Allergies','Médicaments','Ordonnances','Laboratoire','Imagerie','Hospitalisations','Soins','Rendez-vous','Documents','Historique','Audit'];
const initialUser:DemoUser={name:'Dr. Aïssatou Diallo',role:'Médecin',email:'medecin@keneya.demo'};
function can(user:DemoUser, permission:string){let p=permissions[user.role];return p.includes('*')||p.includes(permission)}
function Layout({user,children}:{user:DemoUser;children:React.ReactNode}){let loc=useLocation();return <div className="app-shell"><aside className="side"><Link to="/dashboard" className="brand"><img src="/assets/logo_kdme.png"/><span>Keneya DME</span></Link><nav className="nav">{nav.filter(([path])=>path!='/users'||can(user,'users.manage')).map(([path,i,label])=><Link key={path} className={loc.pathname.startsWith(path)&&path!='/dashboard'||loc.pathname===path?'active':''} to={path}>{i} <span>{label}</span></Link>)}</nav><div className="user-mini"><b>{user.name}</b><br/>{user.role}<br/><small>Démo fictive</small></div></aside><section className="content"><header className="top"><input className="search" placeholder="Recherche globale (démo)"/><div className="top-spacer"/><span className="badge warn">DÉMONSTRATION</span><div className="avatar">AD</div></header>{children}</section></div>}
function Login({onLogin}:{onLogin:(u:DemoUser)=>void}){let [role,setRole]=useState<Role>('Médecin');let [show,setShow]=useState(false);function submit(e:FormEvent){e.preventDefault();onLogin({name:role==='Médecin'?'Dr. Aïssatou Diallo':`${role} Démonstration`,role,email:`${role.toLowerCase()}@keneya.demo`})}return <main className="login"><section className="login-visual"><div className="brand"><img src="/assets/logo_kdme.png"/>Keneya DME</div><div><span className="eyebrow" style={{color:'#9df0e9'}}>Dossier médical électronique</span><h1>Un dossier unique pour des soins plus efficaces.</h1><p>Environnement de démonstration — données fictives, aucune donnée médicale réelle.</p></div><small>Accès réservé aux professionnels autorisés · v0.1.0</small></section><section className="login-panel"><span className="eyebrow">Keneya DME</span><h2>Bienvenue</h2><p className="hint">Choisissez un rôle pour tester les accès de démonstration.</p><form onSubmit={submit}><div className="field"><label>Rôle</label><select value={role} onChange={e=>setRole(e.target.value as Role)}>{demoRoles.map(r=><option key={r}>{r}</option>)}</select></div><div className="field"><label>Email</label><input defaultValue="medecin@keneya.demo" type="email" required/></div><div className="field"><label>Mot de passe</label><div style={{display:'flex',gap:8}}><input type={show?'text':'password'} defaultValue="demo-password" required/><button className="btn ghost" type="button" onClick={()=>setShow(!show)}>{show?'Masquer':'Afficher'}</button></div></div><label className="check"><input type="checkbox" defaultChecked/> Se souvenir de moi</label><button className="btn full">Se connecter</button></form><p className="version">Mot de passe oublié ? · Simulation d’authentification</p></section></main>}
function PageTitle({title,subtitle,action}:{title:string;subtitle:string;action?:React.ReactNode}){return <div className="page-title"><div><h1>{title}</h1><p>{subtitle}</p></div>{action}</div>}
function Dashboard(){return <main className="page"><PageTitle title="Bonjour, Dr. Diallo" subtitle="L’activité médicale de votre établissement." action={<Link className="btn" to="/patients">＋ Nouveau patient</Link>}/><div className="grid kpis">{[['Patients du jour','24'],['Consultations','18'],['Rendez-vous','11'],['Hospitalisés','7'],['Examens en attente','6'],['Ordonnances','14']].map(([x,n])=><div className="card" key={x}><span className="label">{x}</span><div className="kpi-value">{n}</div><span className="trend">↗ Activité du jour</span></div>)}</div><div className="grid two"><section className="card"><h3>Activité médicale</h3><span className="label">Consultations des 7 derniers jours</span><div className="chart">{[45,65,55,88,72,60,83].map((h,i)=><div className="bar" style={{height:`${h}%`}} key={i}/>)}</div></section><section className="card"><h3>Actions rapides</h3><div className="activity"><Link to="/patients">＋ Nouveau patient</Link><Link to="/patients/1?tab=Consultations">＋ Nouvelle consultation</Link><Link to="/patients/1?tab=Ordonnances">＋ Nouvelle ordonnance</Link><Link to="/appointments">＋ Nouveau rendez-vous</Link></div></section></div></main>}
function Patients(){let [items,setItems]=useState<Patient[]>([]),[filter,setFilter]=useState('');let nav=useNavigate();useEffect(()=>{patientService.list().then(setItems)},[]);let visible=useMemo(()=>items.filter(p=>`${p.firstName} ${p.lastName} ${p.number} ${p.phone}`.toLowerCase().includes(filter.toLowerCase())),[items,filter]);return <main className="page"><PageTitle title="Patients" subtitle="Dossiers fictifs de démonstration." action={<button className="btn" onClick={()=>{let firstName=prompt('Prénom fictif');if(firstName){patientService.create({firstName,lastName:'Patient',sex:'Homme',age:30,blood:'O+',phone:'+221 70 000 00 00',allergies:[],conditions:[]}).then(p=>nav(`/patients/${p.id}`))}}}>＋ Nouveau patient</button>}/><section className="card"><div className="toolbar"><input className="search" value={filter} onChange={e=>setFilter(e.target.value)} placeholder="Nom, dossier, téléphone…"/><button className="btn ghost">Filtres</button></div><div className="table-wrap"><table className="table"><thead><tr><th>Patient</th><th>N° dossier</th><th>Sexe</th><th>Âge</th><th>Téléphone</th><th>Alertes</th><th/></tr></thead><tbody>{visible.map(p=><tr key={p.id}><td>{p.firstName} {p.lastName}</td><td>{p.number}</td><td>{p.sex}</td><td>{p.age} ans</td><td>{p.phone}</td><td><span className={p.allergies[0]?.includes('sévère')?'badge danger':'badge'}>{p.allergies.length?'Alerte':'—'}</span></td><td><Link className="btn ghost" to={`/patients/${p.id}`}>Dossier →</Link></td></tr>)}</tbody></table></div></section></main>}
function RecordList({tab}:{tab:string}){let items=records[tab]||[];return <section className="card"><div className="page-title"><div><h3>{tab}</h3><p>Données fictives pour la revue ergonomique.</p></div><button className="btn ghost">＋ Ajouter</button></div>{items.length?<div className="activity">{items.map((r,i)=><div key={i}><b>{r.date} — {r.title}</b><br/><span className="label">{r.detail}</span>{r.status&&<><br/><span className={r.status==='Critique'?'badge danger':'badge'}>{r.status}</span></>}</div>)}</div>:<div className="empty">Aucune donnée de démonstration.</div>}</section>}
function PatientRecord(){let {id='1'}=useParams(),[p,setP]=useState<Patient>();let loc=useLocation();let tab=new URLSearchParams(loc.search).get('tab')||'Résumé';useEffect(()=>{patientService.get(id).then(setP)},[id]);if(!p)return <main className="page">Chargement du dossier…</main>;return <main className="page"><Link className="btn ghost" to="/patients">← Patients</Link><section className="card" style={{marginTop:15}}><div className="patient-head"><div className="patient-photo">{p.firstName[0]}{p.lastName[0]}</div><div><h1>{p.firstName} {p.lastName}</h1><p className="label">{p.number} · {p.age} ans · {p.sex} · Groupe {p.blood} · {p.phone}</p></div></div><div className="alerts">{p.allergies.map(a=><div className="alert" key={a}>⚠ <b>ALLERGIE</b><br/>{a}</div>)}{p.conditions.map(c=><div className="alert" key={c}>⚠ <b>CONDITION CHRONIQUE</b><br/>{c}</div>)}</div><div className="tabs">{dmeTabs.map(t=><Link key={t} className={tab===t?'active':''} to={`/patients/${id}?tab=${t}`}>{t}</Link>)}</div></section>{tab==='Résumé'?<div className="grid two"><RecordList tab="Consultations"/><RecordList tab="Historique"/></div>:<RecordList tab={tab}/>}</main>}
function Module({name}:{name:string}){return <main className="page"><PageTitle title={name} subtitle="Module de démonstration avec données fictives."/><RecordList tab={name==='Rendez-vous'?'Rendez-vous':name}/></main>}
function Sms(){let [result,setResult]=useState('');return <main className="page"><PageTitle title="Service SMS" subtitle="Simulation uniquement — aucun SMS réel n’est envoyé."/><div className="grid two"><section className="card"><h3>Nouvelle notification</h3><button className="btn" onClick={async()=>setResult((await smsService.send('+221 70 000 10 01','Rappel de rendez-vous Keneya')).status)}>Simuler l’envoi</button>{result&&<p className="trend">Statut simulé : {result}</p>}</section><RecordList tab="Historique"/></div></main>}
function App(){let [user,setUser]=useState<DemoUser|null>(null);if(!user)return <Login onLogin={setUser}/>;return <Layout user={user}><Routes><Route path="/dashboard" element={<Dashboard/>}/><Route path="/patients" element={<Patients/>}/><Route path="/patients/:id" element={<PatientRecord/>}/><Route path="/consultations" element={<Module name="Consultations"/>}/><Route path="/appointments" element={<Module name="Rendez-vous"/>}/><Route path="/laboratory" element={<Module name="Laboratoire"/>}/><Route path="/imaging" element={<Module name="Imagerie"/>}/><Route path="/hospitalizations" element={<Module name="Hospitalisations"/>}/><Route path="/prescriptions" element={<Module name="Ordonnances"/>}/><Route path="/documents" element={<Module name="Documents"/>}/><Route path="/sms" element={<Sms/>}/><Route path="/users" element={<Module name="Utilisateurs"/>}/><Route path="/audit" element={<Module name="Audit"/>}/><Route path="/settings" element={<Module name="Paramètres"/>}/><Route path="*" element={<Navigate to="/dashboard" replace/>}/></Routes></Layout>}
export default App;
